version: "2"
linters:
  settings:
    staticcheck:
      dot-import-whitelist:
        - github.com/hanzo-fi/ledger/deployments/pulumi/pkg/common
        - github.com/hanzo-fi/ledger/deployments/pulumi/pkg/utils
        - github.com/formancehq/go-libs/v5/pkg/types/collections
